### ISSUE TITLE
Error running svm_scanner.py

### ISSUE THREAD

**Issue by lch14forever** [CSB5/atminter#1]
23:37:34|lichenhao@LiChenhao|atminter$ ./src/main/python/SVM/svm_scanner.py data/svms/full_trained_svm.p data/example/svm_test -o data/example/svm_test_output/
LOADING SVM:  data/svms/full_trained_svm.p
{'tfidf__encoding': 'utf-8', 'tfidf__max_df': 1.0, 'tfidf__sublinear_tf': False, 'tfidf__smooth_idf': True, 'clf__max_iter': -1, 'tfidf__use_idf': True, 'tfidf__binary': False, 'tfidf__analyzer': 'word', 'clf__cache_size': 200, 'clf__shrinking': True, 'tfidf__decode_error': 'strict', 'tfidf__strip_accents': None, 'tfidf__token_pattern': '(?u)\b\w\w+\b', 'tfidf__stop_words': None, 'tfidf__min_df': 1, 'clf__verbose': False, 'clf__class_weight': 'auto', 'clf__coef0': 0.0, 'tfidf__norm': 'l2', 'tfidf__lowercase': True, 'tfidf': TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\b\w\w+\b', tokenizer=None, use_idf=True,
        vocabulary=None), 'clf__degree': 3, 'tfidf__tokenizer': None, 'tfidf__input': 'content', 'clf__gamma': 0.0, 'clf__probability': False, 'tfidf__ngram_range': (1, 1), 'clf__C': 1, 'clf__decision_function_shape': None, 'tfidf__preprocessor': None, 'tfidf__vocabulary': None, 'tfidf__max_features': None, 'clf': SVC(C=1, cache_size=200, class_weight='auto', coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False), 'clf__tol': 0.001, 'steps': [('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\b\w\w+\b', tokenizer=None, use_idf=True,
        vocabulary=None)), ('clf', SVC(C=1, cache_size=200, class_weight='auto', coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))], 'clf__kernel': 'linear', 'clf__random_state': None, 'tfidf__dtype': <class 'numpy.int64'>}
FILE NUMBER:  0
analysing pair 0/1
data/example/svm_test/Lactobacillus_crispatus#Gardnerella_vaginalis.json
Traceback (most recent call last):
  File "./src/main/python/SVM/svm_scanner.py", line 58, in <module>
    if temp.summary["NEG "] != "1":
KeyError: 'NEG '

**Comment by Klim314** [comment]
Error was keys left over from before refactor. Unconverted keys have been converted to new format.
